/* DO NOT CHANGE ANYTHING BETWEEN THIS LINE AND THE ONE BELOW */
const _ = {};
/* DO NOT CHANGE ANYTHING ABOVE THIS LINE. */

/* DO NOT CHANGE ANYTHING BETWEEN THIS LINE AND THE ONE BELOW */
module.exports = _;
/* DO NOT CHANGE ANYTHING ABOVE THIS LINE. */
